### ISSUE TITLE
retry_record.xml存在代码错误问题

### ISSUE THREAD

**Issue by liangliang520348** [alibaba/SmartEngine#101]
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
        PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.alibaba.smart.framework.engine.persister.database.dao.ActivityInstanceDAO">
应改为 
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
        PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.alibaba.smart.framework.engine.persister.database.dao.RetryRecordDAO">

**Comment by liangliang520348** [comment]
请看下是不是代码错误问题

**Comment by vavi** [comment]
应该是什么？ 这段特性主要是为了写个 demo，支持下复杂场景下的 retry
