### ISSUE TITLE
如何抛出异常

### ISSUE THREAD

**Issue by duoling55** [alibaba/SmartEngine#109]
客户停留在等待节点，前端调用后端接口，后端调用signl方法后后，流程引擎会找到该等待节点，执行等待节点对应的service类里的业务逻辑。执行业务逻辑报的错如何抛给前端呀

![0903](https://github.com/user-attachments/assets/491107d1-9c0c-413b-813c-949801222b31)

**Comment by duoling55** [comment]
流程引擎找到等待节点的service类，并且执行这个类的方法，这个操作是异步的吗

**Comment by duoling55** [comment]
> 流程引擎找到等待节点的service类，并且执行这个类的方法，这个操作是异步的吗

操作是同步的

**Comment by duoling55** [comment]
> 客户停留在等待节点，前端调用后端接口，后端调用signl方法后后，流程引擎会找到该等待节点，执行等待节点对应的service类里的业务逻辑。执行业务逻辑报的错如何抛给前端呀
> 
> ![0903](https://private-user-images.githubusercontent.com/58331348/363822174-491107d1-9c0c-413b-813c-949801222b31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNDkwMzksIm5iZiI6MTcyNTM0ODczOSwicGF0aCI6Ii81ODMzMTM0OC8zNjM4MjIxNzQtNDkxMTA3ZDEtOWMwYy00MTNiLTgxM2MtOTQ5ODAxMjIyYjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA3MzIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MGU1ZDQ5OTc1ZmM0YmVjMjkyMjU2NTQ2NGVlNzlkYTBmNzQ5YjNhMzQ1YTQyN2Y4MDQxZDU0MzA2NDhkODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wZZRNREJd1JbrhOLm0hQN7tUB0Qs-zuU_657g8-3I10)

是同步接口，可以直接抛给前端。

**Comment by vavi** [comment]
嗯，复杂的场景可以看  https://github.com/alibaba/SmartEngine/wiki/SmartEngine-UserGuide--Chinese-Version-(%E4%B8%AD%E6%96%87%E7%89%88)#api-doc 文档中说的到`ExceptionProcessor`来处理
