### ISSUE TITLE
RetryService无法自动注入springbboot容器

### ISSUE THREAD

**Issue by duoling55** [alibaba/SmartEngine#110]
项目引入了smart-engine-extension-retry-common的依赖，但是@autowird retryService,报以下错误，expected at least 1 bean which qualifies as autowire candidate。

**Comment by duoling55** [comment]
![0909](https://github.com/user-attachments/assets/054886a3-a5f0-449c-a790-969f112ccbff)

**Comment by duoling55** [comment]
解决办法：
1、调用SmartEngine的init方法，初始化smartEngine，把配置类放在内存里
2、调用DefaultRetryService的start方法，初始化重试类，把内存的配置类传入此方法
之后其它地方就可以自动注入DefaultRetryService了

**Comment by duoling55** [comment]
解决办法：
1、调用SmartEngine的init方法，初始化smartEngine，把配置类放在内存里
2、调用DefaultRetryService的start方法，初始化重试类，把内存的配置类传入此方法
之后其它地方就可以自动注入DefaultRetryService了

**Comment by duoling55** [comment]
收到感谢

**Comment by gannyee** [comment]
@vavi 基于数据库的重试是不是这个地方写的有问题。基于database的模式数据库的重试。

<img width="963" alt="Image" src="https://github.com/user-attachments/assets/398f09c0-10d6-4e9d-b728-3f7d384c32e9" />
