### ISSUE TITLE
目前的master分支缺少ServiceTaskBehavior 导致xml配置了serviceTask都会报错

### ISSUE THREAD

**Issue by bojiw** [alibaba/SmartEngine#14]
目前的master分支缺少ServiceTaskBehavior 导致xml配置了serviceTask都会报错

**Comment by vavi** [comment]
有可以复现的testcase? 我来修复下。 具体异常是什么。

**Comment by bojiw** [comment]
执行执行SmartPropertiesTest 这个会报NullPointerException 
DefaultRepositoryCommandService#269 获取的activityBehavior为空

**Comment by vavi** [comment]
嗯 谢谢。 这个不错不应该的。 我来修复下。

**Comment by vavi** [comment]
嗯，这个错误不应该发生的。我来修复下。

**Comment by vavi** [comment]
非常感谢，已经修复了。 见 2.1.2 版本。  若有问题，麻烦再反馈下。

**Comment by bojiw** [comment]
嗯嗯 好的
