### ISSUE TITLE
请提供完整示例demo

### ISSUE THREAD

**Issue by spyvip** [alibaba/SmartEngine#16]
````
http://gitlab.alibaba-inc.com/smart-framework/simplest-bpm-demo
````

test类有点看不懂~~~

**Comment by vavi** [comment]
你是内网用户？ 方便的话，钉我下吧。

**Comment by spyvip** [comment]
> 你是内网用户？ 方便的话，钉我下吧。

@vavi sorry我是外网用户~~~~~

**Comment by vavi** [comment]
那上面那个链接是哪里看到的。。。 我需要修改下哈。 

另外，简单demo的话，我会补充的哈。

**Comment by spyvip** [comment]
@vavi from baidu search egine.

**Comment by vavi** [comment]
好吧 没搜出来。

**Comment by vavi** [comment]
DataBase简单例子，见源码：`DataBaseAuditProcessExample`
Custom简单例子，见源码：`BasicProcessTest`

 整体来说，SmartEngine的使用还是比较简单的。 有具体问题再单独开贴聊下哈。
