### ISSUE TITLE
有配套的modeler设计器或idea插件么

### ISSUE THREAD

**Issue by yfcchilly** [alibaba/SmartEngine#18]
bpmn和标准的语法还是有差异。请问有配套的设计器和idea插件么，开发起来感觉没有那么习惯。

另外提个小意见，如果流程定义，持久化在远端存储里，在应用端采用custom来跑。两个extension使用起来，都比较费劲：
1）应用端，集成client和custom扩展包，但是需要从远端加载流程定义，并deploy到本地，需要自己实现storage和dao层
2）管理端，只需要deploy流程定义到远程存储，只能使用mysql扩展，但是facade没有只deploy远端的接口。只能直接从dao层开始自己包装。

**Comment by vavi** [comment]
1.bpmn和标准的语法还是有差异-- 这么最近我们在打算完全兼容bpmn语义。 你有哪些场景需要优先实现的吗？ 可以这里反馈下
2. 现在 deploy facade 没有支持 custom模式，这块尚未排进日程。

**Comment by yfcchilly** [comment]
现在业务技术调研下来可以考虑使用，主要有两个顾虑：

**Comment by yfcchilly** [comment]
虽然也可以魔改，管控端组合下parseXML+storage也能实现。对于custom端，如果要load远端流程，也可以通过调用远程代理服务，query到流程，再deploy到内存。但是个人觉得如果extension能解决好

**Comment by vavi** [comment]
1. 社区标准的bpmn工具生产的流程文件又不太兼容 --这个你们主要使用bpmn.js吗？
----
管理端准备嵌入式web的modeler，应用端使用custom来跑。对于扩展的需求是：
2.1 mysql扩展，支持配置deploy是否可以跳过memory，直接只持久化到远端存储。管理端使用
2.2 custom扩展，支持从远端数据库load & deploy到memory。应用端使用

这块目前需要业务团队自己扩展下，特别是集群环境下，还需要考虑数据一致性。

**Comment by yfcchilly** [comment]
是的。Camunda 或者 bpmn.js

**Comment by vavi** [comment]
今天发布了2.5.0 版本，兼容了Camunda 的设计器（smart:class,smart:properties,smart:eventListener 3个特性可以无缝兼容）。
