### ISSUE TITLE
并行网关Session的NPE问题

### ISSUE THREAD

**Issue by yfcchilly** [alibaba/SmartEngine#19]
custom模式，并行网关在执行的时候有一个NPE的bug，线程池在复用的时候，多次运行同一个process，会出现一个奇怪的现象:
1) 首次运行CustomExecutionInstanceStorage都可以拿到currentSession
2) 多次运行，线程池都是复用的情况下，开始出现NPE。
3) 增大线程池后，NPE首次出现的时机延缓。差不多都是复用的线程后，最终还是出现NPE

初步怀疑InheritableThreadLocal，线程池中ThreadLocal变量拷贝有点问题。docs中注释有声明只要在子线程创建的时候，才会拷贝线程变量。

`Inheritable thread-local variables are used in preference to ordinary thread-local variables when the per-thread-attribute being maintained in the variable (e.g., User ID, Transaction ID) must be automatically transmitted to any child threads that are created`

以下是堆栈内容

`java.lang.NullPointerException: null
	at com.alibaba.smart.framework.engine.persister.custom.CustomExecutionInstanceStorage.findActiveExecution(CustomExecutionInstanceStorage.java:95) 
	at com.alibaba.smart.framework.engine.bpmn.behavior.gateway.ParallelGatewayBehavior.enter(ParallelGatewayBehavior.java:107) 
	at com.alibaba.smart.framework.engine.pvm.impl.DefaultPvmActivity.enter(DefaultPvmActivity.java:32) 
	at com.alibaba.smart.framework.engine.behavior.base.AbstractActivityBehavior.leave(AbstractActivityBehavior.java:127) 
	at com.alibaba.smart.framework.engine.pvm.impl.DefaultPvmActivity.execute(DefaultPvmActivity.java:86) 
	at com.alibaba.smart.framework.engine.pvm.impl.DefaultPvmActivity.enter(DefaultPvmActivity.java:43) 
	at com.alibaba.smart.framework.engine.bpmn.behavior.gateway.ParallelGatewayBehavior$PvmActivityTask.call(ParallelGatewayBehavior.java:183) 
	at com.alibaba.smart.framework.engine.bpmn.behavior.gateway.ParallelGatewayBehavior$PvmActivityTask.call(ParallelGatewayBehavior.java:171) 
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) 
	at java.util.concurrent.FutureTask.run(FutureTask.java) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
	at java.lang.Thread.run(Thread.java:748) `

另外两个bug上报下，下面是修改后的diff
1) InstanceUtil的NPE
2) 多线程导致的list迭代异常ConcurrentModificationException

[mr.log](https://github.com/alibaba/SmartEngine/files/5115719/mr.log)

**Comment by vavi** [comment]
感谢反馈。

1. 可否提供下可复现问题的testcase？
2. 多次运行同一个process 怎么理解？

**Comment by vavi** [comment]
目前不支持，也不应该并发驱动单个ExecutionInstance执行。

**Comment by yfcchilly** [comment]
并不是并发驱动单个ExecutionInstance。
<img width="753" alt="流程图" src="https://user-images.githubusercontent.com/21029247/91171108-867a3080-e70c-11ea-8c13-abc8befe4d2f.png">

以上的一个process，通过本地xml启动deploy，采用custom模式运行。spring启动了一个app，通过http来触发反复执行某个process。fork-join采用自己设置的线程池。代码如下：
`public class SmartEngineService {

    private SmartEngine smartEngine;

    public SmartEngineService(SmartEngine smartEngine) {
        this.smartEngine = smartEngine;
    }

    public void executeProcess(String processInstanceId, String version,
                               Map<String, Object> request,
                               Map<String, Object> response) {
        try {
            PersisterSession.create();
            ProcessCommandService processCommandService = smartEngine.getProcessCommandService();
            processCommandService.start(processInstanceId, version, request, response);
        } finally {
            PersisterSession.destroySession();
        }
    }
}`

**Comment by yfcchilly** [comment]
顺便问一下，会支持subProcess么。现在变相通过callActivity实现，但是两个Process定义是分离的。感觉不如原生的subProcess在canvas上直观

**Comment by vavi** [comment]
好的，明天你的意思了。 我这几天来修复下。 SubProcess 短期内不太考虑，现在来说的话，callActivity 使用量还是很小的，并且实现和测试场景还不太充分。 先至少等callActivity 功能稳定下来。

**Comment by vavi** [comment]
> custom模式，并行网关在执行的时候有一个NPE的bug，线程池在复用的时候，多次运行同一个process，会出现一个奇怪的现象:
> 
> 1. 首次运行CustomExecutionInstanceStorage都可以拿到currentSession
> 2. 多次运行，线程池都是复用的情况下，开始出现NPE。
> 3. 增大线程池后，NPE首次出现的时机延缓。差不多都是复用的线程后，最终还是出现NPE
> 
> 初步怀疑InheritableThreadLocal，线程池中ThreadLocal变量拷贝有点问题。docs中注释有声明只要在子线程创建的时候，才会拷贝线程变量。
> 
> `Inheritable thread-local variables are used in preference to ordinary thread-local variables when the per-thread-attribute being maintained in the variable (e.g., User ID, Transaction ID) must be automatically transmitted to any child threads that are created`
> 
> 以下是堆栈内容
> 
> `java.lang.NullPointerException: null at com.alibaba.smart.framework.engine.persister.custom.CustomExecutionInstanceStorage.findActiveExecution(CustomExecutionInstanceStorage.java:95) at com.alibaba.smart.framework.engine.bpmn.behavior.gateway.ParallelGatewayBehavior.enter(ParallelGatewayBehavior.java:107) at com.alibaba.smart.framework.engine.pvm.impl.DefaultPvmActivity.enter(DefaultPvmActivity.java:32) at com.alibaba.smart.framework.engine.behavior.base.AbstractActivityBehavior.leave(AbstractActivityBehavior.java:127) at com.alibaba.smart.framework.engine.pvm.impl.DefaultPvmActivity.execute(DefaultPvmActivity.java:86) at com.alibaba.smart.framework.engine.pvm.impl.DefaultPvmActivity.enter(DefaultPvmActivity.java:43) at com.alibaba.smart.framework.engine.bpmn.behavior.gateway.ParallelGatewayBehavior$PvmActivityTask.call(ParallelGatewayBehavior.java:183) at com.alibaba.smart.framework.engine.bpmn.behavior.gateway.ParallelGatewayBehavior$PvmActivityTask.call(ParallelGatewayBehavior.java:171) at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) at java.util.concurrent.FutureTask.run(FutureTask.java) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) `
> 
> 另外两个bug上报下，下面是修改后的diff
> 
> 1. InstanceUtil的NPE
> 2. 多线程导致的list迭代异常ConcurrentModificationException
> 
> [mr.log](https://github.com/alibaba/SmartEngine/files/5115719/mr.log)

这个mr ，你方便发个pull request？ 我来合并下。

**Comment by yfcchilly** [comment]
pr已提交
