### ISSUE TITLE
并行问题

### ISSUE THREAD

**Issue by Leonardawp** [alibaba/SmartEngine#24]
@Override
    public void enter(ExecutionContext context) {

        ActivityBehavior behavior = this.getBehavior();
        boolean needPause= behavior.enter(context, this);

        fireEvent(context,PvmEventConstant.ACTIVITY_START.name());

        if (needPause) {

            // break;
            return;
        }

        this.execute(context);
    }

这里要不做个特判？behavior instanceof ParallelGatewayBehavior 则进行一些并行特殊处理，现在有npe问题，后面this.execute(context);也很奇怪

**Comment by vavi** [comment]
这个目前不需要特殊判断。ParallelGatewayBehavior的实现有点问题，我正在修复。 我在 https://github.com/alibaba/SmartEngine/issues/19  统一解决下。
