### ISSUE TITLE
有未来的演进路线图嘛？

### ISSUE THREAD

**Issue by poal222** [alibaba/SmartEngine#25]
仔细阅读了一下，感觉挺不错，但有几点疑虑
1、文档太少，都2.0版本了，没有案例，没有starter，没有sample，对于我们团队来说，社区支持还是很重要的；
2、有未来的技术或者版本推进路线图嘛，也好团队评估使用的前景如何
3、建议文档中，多增加点场景，例如，节点权限集成等内容

**Comment by vavi** [comment]
感谢反馈
1. 目前没有starter的必要，直接jar依赖就好了哈。 2. SAMPLE 的确是个问题，不过有个典型的test可以参考的：DataBase简单例子，见源码：`DataBaseAuditProcessExample`
Custom简单例子，见源码：`BasicProcessTest`
2. 现在技术演进的方向是比较确定的，比如说完善对子流程和并行网关的支持；提升性能；设计器开源等。 
3. 权限这块基本交给业务团队了，目前SmartEngine 比较聚焦在完善引擎本身。不过我们提供了TaskDispatcher这种机制，帮助用户集成。
