### ISSUE TITLE
能提供个示例代码就更好了

### ISSUE THREAD

**Issue by huoxudong125** [alibaba/SmartEngine#3]
能提供个示例代码就更好了，wiki 打不开一直跳转到代码页

**Comment by vavi** [comment]
嗯 中文文档更新中 最近在开发一些新特性。

**Comment by vavi** [comment]
maven 仓库一直提交不了，oss.sonatype.org 非常慢，我在想办法解决。  例子基本都在test 里面。 
WIKI 先更新了一版了：   https://github.com/alibaba/SmartEngine/wiki/SmartEngine-UserGuide--Chinese-Version-(%E4%B8%AD%E6%96%87%E7%89%88)

**Comment by vavi** [comment]
终于在maven 官方仓库发布了，有相关使用问题，可以随时交流。
