### ISSUE TITLE
2.2.3.2版本InstanceAccessor实现类必须实现spring托管bean的疑问

### ISSUE THREAD

**Issue by JannLim** [alibaba/SmartEngine#34]
看了2.2.3.2版本的更新内容，storage-mysql和storage-mongodb中都取消了对spring的依赖，但是却利用InstanceAccessor的实现类来实现spring容器中对象的获取，这样就规定了InstanceAccessor的实现类必须能从spring中获取对象，同时storage-mysql也是基于mybatis来进行数据的持久化。所以想请问一下，未来有将这块数据持久化相关内容完全脱离spring和mybatis的规划吗？

**Comment by vavi** [comment]
看了2.2.3.2版本的更新内容，storage-mysql和storage-mongodb中都取消了对spring的依赖，但是却利用InstanceAccessor的实现类来实现spring容器中对象的获取，这样就规定了InstanceAccessor的实现类必须能从spring中获取对象
--对的，主要是为了减少对SpringContextUtil这样的依赖，减少配置复杂度，提升优雅性。 另外一方面，一般InstanceAccessor实现类都需要依赖Spring，去获取Delegation对象。 再加上，Spring也已经成为事实标准了。所以SmartEngine在实际时，尽量是减少依赖，但是在运行时的最佳实践，一般还是依赖SpringFramework的。 

同时storage-mysql也是基于mybatis来进行数据的持久化。所以想请问一下，未来有将这块数据持久化相关内容完全脱离spring和mybatis的规划吗？
--- 现在的持久化是基于mybatis，为什么要脱离呢spring和mybatis？ 不过，如果你有自定义的需求，也可以实现 com.alibaba.smart.framework.engine.instance.storage 这个package 内部接口

**Comment by JannLim** [comment]
目前是没有脱离spring和mybatis的需求，就是觉得比较奇怪，因为storage-mysql间接依赖了spring和mybatis，但是如果作为直接使用方而言，如果不对源码进行阅读，这两个地方是上层业务需要被关注的店，所以可能都会被使用者误踩坑

**Comment by vavi** [comment]
嗯，wiki我看看更新下。
