### ISSUE TITLE
文档太少啦，也没找到示例

### ISSUE THREAD

**Issue by c8679724** [alibaba/SmartEngine#4]

**Comment by vavi** [comment]
maven 仓库一直提交不了，oss.sonatype.org 非常慢，我在想办法解决。  例子基本都在test 里面。 
WIKI 先更新了一版了：   https://github.com/alibaba/SmartEngine/wiki/SmartEngine-UserGuide--Chinese-Version-(%E4%B8%AD%E6%96%87%E7%89%88)

**Comment by vavi** [comment]
终于在maven 官方仓库发布了，有相关使用问题，可以随时交流。
