### ISSUE TITLE
关于参数传递的问题。

### ISSUE THREAD

**Issue by ningchunlei** [alibaba/SmartEngine#46]
好像不支持显示支持方法调用和参数传递。 
`<serviceTask id="executeTask" name="ExecuteTask"
       smart:class="com.alibaba.simplest.bpm.util.AuditProcessServiceTaskDelegation">
</serviceTask>`

这个里边能传递参数么例如
` <serviceTask id="executeTask" name="ExecuteTask"
       smart:class="springBean.method(param1,param2)">
</serviceTask>`

如果要实现这个需要怎么扩展呢， 能一些思路么。 

显示的调用方法，开发同学看起来更直观， 不然针对每个任务都需要写个代理类

**Comment by vavi** [comment]
这个你可以通过覆写`DelegationExecutor` 来实现；但是传参方面，需要你做些约定。

**Comment by ningchunlei** [comment]
> 这个你可以通过覆写`DelegationExecutor` 来实现；但是传参方面，需要你做些约定。

你们后续有计划在这个方面做些事情么

**Comment by vavi** [comment]
目前没有计划，主要这里的需求共性较少。 如果是比较典型的需求，是可以默认支持下。 你有什么好的建议方案吗
