### ISSUE TITLE
中文版UserGuide错别字修改

### ISSUE THREAD

**Issue by XYF001** [alibaba/SmartEngine#51]
**url:** [中文版UserGuide](https://github.com/alibaba/SmartEngine/wiki/SmartEngine-UserGuide--Chinese-Version-(%E4%B8%AD%E6%96%87%E7%89%88))
**origin:** 值**的**一提
**expected:** 值**得**一提

![image](https://user-images.githubusercontent.com/24812746/136573959-05283a39-58d5-4c5b-8bad-0c971f3eee9d.png)

**Comment by vavi** [comment]
感谢反馈，已修复。
