### ISSUE TITLE
对于持久化工作流模式业务逻辑发生exception的处理想法

### ISSUE THREAD

**Issue by AttanWu** [alibaba/SmartEngine#53]
现在看到SM的主要推进一个process运行的入口主要是start和signal,分别是流程的开始，和暂停之后的恢复运行
在典型的需要持久化的场景下，很可能运行时的节点内业务逻辑会发生exception,这种情况SM本身没有做任何的异常处理，也没有catch,直接会导致整个流程运行直接报错抛出exception,所有运行完的流程节点不会完成持久化信息全部丢失，这块方面想做一些贡献，请问下作者，有无这方面的考虑或者是方向？

ps:调研了集中节点内异常处理的方式
![image](https://user-images.githubusercontent.com/16112546/137766733-ca5efff9-10b2-459e-858d-fa1a97421f6a.png)
![image](https://user-images.githubusercontent.com/16112546/137766801-764dec71-e378-4467-b719-37db91169bc6.png)

**Comment by vavi** [comment]
SE 的思路和Activiti 不太一样，你看下这个：`ExceptionProcessor`，看看能否满足你的需求。
