### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by RedA1ert** [alibaba/SmartEngine#54]
有没有稳定的版本可以用于生产使用？有没有搭配的流程配置页面？

**Comment by vavi** [comment]
可以关注下changelog，目前2.6.1 是稳定的； 目前界面侧没有提供。

**Comment by RedA1ert** [comment]
中央仓库最新版本是2.6.0 ，请问有没有比较完整的案例或者文档帮助参考一下，感谢

发自我的iPhone

**Comment by RedA1ert** [comment]
> 。

**Comment by vavi** [comment]
嗯 maven 仓库好像有点问题，发布了迟迟没更新。 2.6.0也是可以的。 

关于设计器问题，可以参考：
https://github.com/alibaba/SmartEngine/wiki/SmartEngine-UserGuide--Chinese-Version-(%E4%B8%AD%E6%96%87%E7%89%88)#%E6%8E%A8%E8%8D%90%E5%93%AA%E4%B8%AA%E6%B5%81%E7%A8%8B%E8%AE%BE%E8%AE%A1%E5%99%A8
