### ISSUE TITLE
mysql 数据库自增 主键没有回填

### ISSUE THREAD

**Issue by whzayj1314** [alibaba/SmartEngine#59]
useGeneratedKeys="true"

**Comment by vavi** [comment]
se和mybatis分别用的哪个版本? mybatis 可能需要升级下。。

**Comment by whzayj1314** [comment]
> se和mybatis分别用的哪个版本? mybatis 可能需要升级下。。

应该是没测试过自增吧。我id生成器返回null，使用数据库自增，蛮多地方都报错，因为有些地方还没执行插入，id还没有。我修改了一下 暂时可以用

**Comment by vavi** [comment]
嗯 现在主场景一般都是实现ID生产器接口的。 自增场景，我记得以前测试过，不过当时id生成器应该是给了个数值（没有返回null），然后在插入时，会使用db的自增。
