### ISSUE TITLE
顺序会签导致流产abort

### ISSUE THREAD

**Issue by whzayj1314** [alibaba/SmartEngine#66]
顺序会签中审批节点驳回后,流程直接abort。这个貌似不是很合理

**Comment by vavi** [comment]
我记得是支持any/all 模式的。 或者表达式默认的。 你用的应该是all模式。

**Comment by whzayj1314** [comment]
一样都是abort，不管是any还是all，context一旦设置停止流程，activity就无法leave走下面的流程了

**Comment by vavi** [comment]
我这边没有复现，你那边有稳定的testcase吗？

**Comment by whzayj1314** [comment]
any模式确实是可以的，只是可能我这边的判断不太一样，我们业务上的是一个层级一些人都可以审批，但是顺序会签的话，是以层级来的，目前sm是以人来算的，所以流程没办法流转，我魔改了一下，目前稳定

**Comment by vavi** [comment]
嗯  ，SE 里面没有层级这种东西，需要你去扩展。 可以基于扩展点实现，不需要改源码，做到无侵入。
