### ISSUE TITLE
示例太少

### ISSUE THREAD

**Issue by qinliang373** [alibaba/SmartEngine#80]
目前项目示例太少，希望能多增加些示例，提供与springboot整合jar包。

**Comment by qinliang373** [comment]
目前项目示例不够清晰，源码注释不全且不够详细，希望能完善代码示例，完善代码注释，提供与springboot整合jar包。

**Comment by vavi** [comment]
嗯 会增加些示例，开发中了  ； springboot jar 我感觉没啥必要啊，直接二方库依赖就好了。
