### ISSUE TITLE
请问jumpTo和jumpFrom的使用场景是什么

### ISSUE THREAD

**Issue by SpringStudent** [alibaba/SmartEngine#84]
感谢提供了如此优秀的工作流引擎，请教下jumpTo和jumpFrom的使用场景

**Comment by vavi** [comment]
主要适用于自由流场景， jumpTo 是跳到目标环节，jumpFrom是从指定环节开始往后流转。不过这两个api是unsafe的，调用前可能需要清理部分数据；

**Comment by SpringStudent** [comment]
清理那部分数据呢？有完善的使用用例吗

**Comment by vavi** [comment]
这个没有我，就是本质上根据业务场景需要，进行数据订正，清理掉垃圾数据即可。

**Comment by SpringStudent** [comment]
好的，感谢大佬回复
