### ISSUE TITLE
mapper.xml加载不了

### ISSUE THREAD

**Issue by qingdaoDuida** [alibaba/SmartEngine#87]
Invalid bound statement (not found)  提示找不到dao里面的方法

**Comment by qingdaoDuida** [comment]
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/15310241/211243340-0ad49e54-783d-4519-8379-eb470c46b727.png">

**Comment by vavi** [comment]
你是在自己的工程里面运行失败？还是直接运行源码里面的test失败？

**Comment by qingdaoDuida** [comment]
> 你是在自己的工程里面运行失败？还是直接运行源码里面的test失败？

找到原因了，我们项目用的是mybatis-plus  配置xml加载路径时用的mybatis属性导致的

**Comment by vavi** [comment]
好的 ~
