### ISSUE TITLE
为什么我把数据源从H2替换为mysql后，运行示例，数据库里没有产生数据？

### ISSUE THREAD

**Issue by java-my-life** [alibaba/SmartEngine#92]
为什么我把数据源从H2替换为mysql后，运行示例，数据库里没有产生数据？
看日志sql语句也都打印了，运行也成功了，把TaskServiceTest测试类上的@Transactional注解去掉就可以产生数据，是哪里配置了事务回滚吗？

**Comment by vavi** [comment]
看下这个：https://blog.csdn.net/user2025/article/details/108909361
